---
# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "imewei"
    assignees:
      - "imewei"

  # Python package dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
      - "automated"
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "imewei"
    assignees:
      - "imewei"
    # Group updates for related packages
    groups:
      jax-stack:
        patterns:
          - "jax*"
        update-types:
          - "minor"
          - "patch"
      numpy-scipy:
        patterns:
          - "numpy"
          - "scipy"
        update-types:
          - "minor"
          - "patch"
      testing:
        patterns:
          - "pytest*"
          - "hypothesis"
        update-types:
          - "minor"
          - "patch"
      linting:
        patterns:
          - "ruff"
          - "black"
          - "mypy"
        update-types:
          - "minor"
          - "patch"
    # Allow only specific updates for critical dependencies
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
        update-types: ["security"]
    # Ignore alpha/beta/rc releases for stability
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Major updates require manual review
    # Version constraints
    versioning-strategy: increase

  # Documentation dependencies
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "monthly"
      day: "monday"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "documentation"
      - "automated"
    commit-message:
      prefix: "docs"
