# Dependabot Configuration for NLSQ
# Automatically creates PRs to update dependencies
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    reviewers:
      - "imewei"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Group updates by category
    groups:
      # Core runtime dependencies
      core-dependencies:
        patterns:
          - "numpy"
          - "scipy"
          - "jax*"
          - "matplotlib"
        update-types:
          - "minor"
          - "patch"

      # Testing dependencies
      testing-dependencies:
        patterns:
          - "pytest*"
          - "hypothesis"
        update-types:
          - "minor"
          - "patch"

      # Code quality tools
      code-quality-dependencies:
        patterns:
          - "black"
          - "ruff"
          - "mypy"
          - "pre-commit"
          - "bandit"
          - "pyupgrade"
        update-types:
          - "minor"
          - "patch"

      # Documentation dependencies
      docs-dependencies:
        patterns:
          - "sphinx*"
          - "myst-parser"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 5
    reviewers:
      - "imewei"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Docker (if Dockerfile exists)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 5
    reviewers:
      - "imewei"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"

# Security updates are handled separately with higher priority
# Dependabot security updates are enabled by default for all repositories
