# Pre-commit configuration
# Versions aligned with local environment and pyproject.toml (2025-10-17)
# See REQUIREMENTS.md for dependency management strategy

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2000']
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first
      - id: check-json
      - id: check-ast
      - id: mixed-line-ending
      - id: name-tests-test
        args: ['--pytest-test-first']
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1  # Aligned with local ruff 0.14.1 and pyproject.toml >=0.10.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2  # Aligned with local mypy 1.18.2 and pyproject.toml >=1.10
    hooks:
      - id: mypy
        additional_dependencies: [numpy, jax, types-setuptools, scipy, psutil, types-tqdm]
        args: [--python-version=3.12, --check-untyped-defs]
        files: ^nlsq/
        exclude: ^(tests/|examples/|benchmark/)

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.0
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ['--skip=*.ipynb,*.html', '--ignore-words-list=nd,coo,assertIn']

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.20.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]
        exclude: ^(docs/archive/|benchmark/docs/)

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6  # Security linting (low-level checks only)
    hooks:
      - id: bandit
        args: ['-ll', '--skip=B101,B601,B602,B607']
        files: ^nlsq/
        exclude: ^(tests/|examples/|benchmark/)

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0  # Updated to latest version (Python 3.12+ syntax)
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  # Local hooks for project-specific checks
  - repo: local
    hooks:
      - id: docs-build
        name: Build Sphinx documentation (warnings as errors)
        entry: bash -c 'cd docs && make html SPHINXOPTS="-W --keep-going -q"'
        language: system
        files: ^(docs/|nlsq/.*\.py$|.*\.md$)
        pass_filenames: false
        stages: [manual]  # Run with: pre-commit run --hook-stage manual docs-build
        # Note: -n (nitpicky mode) disabled as too strict for scientific computing library
