version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - graphviz
  jobs:
    pre_build:
      - echo "Building NLSQ documentation..."
    post_build:
      - echo "Documentation build complete"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

formats:
  - pdf
  - epub
  - htmlzip

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt
