# ReadTheDocs configuration for NLSQ
# Updated: 2025-10-08
# Requires: Python 3.12+, NumPy 2.0+
# Dependencies managed via pyproject.toml[docs]

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"  # Aligned with pyproject.toml requires-python >=3.12
  apt_packages:
    - graphviz
  jobs:
    pre_build:
      - echo "Building NLSQ documentation..."
      - echo "Note: This build requires NumPy 2.0+ (breaking change from 1.x)"
      - echo "See REQUIREMENTS.md for dependency details"
    post_build:
      - echo "Documentation build complete"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
  builder: html

formats:
  - htmlzip

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs  # Installs from pyproject.toml[project.optional-dependencies.docs]
    - requirements: docs/requirements.txt  # References pyproject.toml for version info
