name: ✨ Feature Request
description: Suggest a new feature or enhancement for NLSQ
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - imewei

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide details below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        I'm always frustrated when...
        I need to... but currently NLSQ doesn't support...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        I would like NLSQ to support...
        This could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I tried... but it didn't work well because...
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show how you'd like to use this feature (pseudo-code is fine)
      placeholder: |
        ```python
        import nlsq

        # Example of how the feature would be used
        result = nlsq.new_feature(...)
        ```
      value: |
        ```python
        import nlsq

        # Your example here
        ```
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New algorithm
        - Performance improvement
        - New API method
        - Better error handling
        - Documentation improvement
        - Developer tooling
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my work)
        - High (would significantly improve my workflow)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Expected Impact
      description: Who would benefit from this feature? How widely applicable is it?
      placeholder: |
        This would benefit users who...
        This is applicable to...% of use cases
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I am willing to help implement this feature
          required: false
        - label: I can provide test cases or examples
          required: false
        - label: I can help with documentation
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, links, or references about the feature request
      placeholder: |
        Similar implementations in other libraries:
        - SciPy: ...
        - scikit-learn: ...

        Related papers or documentation:
        - https://...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: This feature aligns with NLSQ's goal of GPU/TPU-accelerated curve fitting
          required: true
