name: Validate Notebooks

on:
  pull_request:
    paths:
      - 'examples/notebooks/**/*.ipynb'
      - 'scripts/configure_notebooks.py'
      - 'scripts/notebook_utils/**/*.py'
      - '.github/workflows/validate-notebooks.yml'
  push:
    branches:
      - main
    paths:
      - 'examples/notebooks/**/*.ipynb'
      - 'scripts/configure_notebooks.py'
      - 'scripts/notebook_utils/**/*.py'
      - '.github/workflows/validate-notebooks.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  validate:
    name: Validate Notebook Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better diff analysis

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install uv package manager
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install --system click

      - name: Validate notebooks (dry-run)
        id: validate
        run: |
          echo "🔍 Validating notebook configurations..."
          python scripts/configure_notebooks.py --dry-run --verbose
        continue-on-error: true

      - name: Check validation results
        if: steps.validate.outcome == 'failure'
        run: |
          echo "❌ Notebook validation failed!"
          echo "Some notebooks need configuration updates."
          echo ""
          echo "To fix locally, run:"
          echo "  python scripts/configure_notebooks.py"
          echo ""
          echo "Or use pre-commit hooks:"
          echo "  pre-commit run --hook-stage manual configure-notebooks --all-files"
          exit 1

      - name: Report success
        if: steps.validate.outcome == 'success'
        run: |
          echo "✅ All notebooks properly configured!"

  auto-fix:
    name: Auto-fix Notebook Configuration
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: validate

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv package manager
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install --system click

      - name: Configure notebooks
        id: configure
        run: |
          echo "🔧 Applying notebook configurations..."
          python scripts/configure_notebooks.py --incremental --verbose

          # Check if any files were modified
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes_made=true" >> $GITHUB_OUTPUT
            echo "📝 Notebooks were modified"
          else
            echo "changes_made=false" >> $GITHUB_OUTPUT
            echo "✅ No changes needed"
          fi

      - name: Commit changes
        if: steps.configure.outputs.changes_made == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add examples/notebooks/**/*.ipynb

          git commit -m "ci: auto-configure notebooks

          Applied transformations:
          - Add %matplotlib inline magic
          - Add IPython.display imports
          - Replace plt.show() with display/close pattern

          🤖 Generated with [Claude Code](https://claude.com/claude-code)

          Co-Authored-By: Claude <noreply@anthropic.com>"

          git push

      - name: Comment on PR
        if: steps.configure.outputs.changes_made == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🤖 Notebook Auto-Configuration

              The CI workflow has automatically configured your notebooks:

              ✅ Added \`%matplotlib inline\` magic where needed
              ✅ Added \`from IPython.display import display\` imports
              ✅ Replaced \`plt.show()\` with display/close pattern

              The changes have been committed to this PR.

              ---
              <details>
              <summary>How to configure notebooks locally</summary>

              \`\`\`bash
              # Apply all transformations
              python scripts/configure_notebooks.py

              # Or use pre-commit hooks
              pre-commit run --hook-stage manual configure-notebooks --all-files
              \`\`\`

              See [Notebook Utilities Documentation](../../docs/developer/notebook_utilities.rst) for more information.
              </details>`
            })

  incremental-test:
    name: Test Incremental Processing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv package manager
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install --system click

      - name: Test incremental mode (first run)
        run: |
          echo "📊 Testing incremental processing..."
          python scripts/configure_notebooks.py --incremental --dry-run

      - name: Test incremental mode (second run - should skip)
        run: |
          echo "🔄 Re-running incremental mode (should skip unchanged notebooks)..."
          python scripts/configure_notebooks.py --incremental --dry-run

  parallel-performance:
    name: Test Parallel Processing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv package manager
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install --system click

      - name: Test sequential processing
        run: |
          echo "⏱️ Testing sequential processing..."
          time python scripts/configure_notebooks.py --sequential --dry-run

      - name: Test parallel processing
        run: |
          echo "⚡ Testing parallel processing..."
          time python scripts/configure_notebooks.py --parallel --workers 4 --dry-run
