name: CI Step 4 - Add Job Conditionals

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    if: ${{ matrix.run-condition == 'always' || matrix.run-condition == 'cross-platform' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']
        test-suite: ['fast']
        include:
          # Ubuntu (primary platform) - always runs
          - os: ubuntu-latest
            python-version: '3.12'
            test-suite: 'fast'
            run-condition: 'always'
          # Cross-platform testing
          - os: windows-latest
            python-version: '3.12'
            test-suite: 'fast'
            run-condition: cross-platform

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -e ".[test]"

    - name: Test import
      run: |
        python -c "import nlsq; print(f'NLSQ {nlsq.__version__} imported successfully')"

    - name: Show matrix info
      run: |
        echo "OS: ${{ matrix.os }}"
        echo "Python: ${{ matrix.python-version }}"
        echo "Run condition: ${{ matrix.run-condition }}"