name: CI Simple

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -e ".[test]"

    - name: Test import
      run: |
        python -c "import nlsq; print(f'NLSQ {nlsq.__version__} imported successfully')"
        python -c "from nlsq import curve_fit; print('curve_fit imported successfully')"

    - name: Run basic tests
      run: |
        python -c "
        import nlsq
        import numpy as np
        print('✅ Basic functionality test passed')
        "